//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SC4Ed.rc
//
#define IDS_APP_TITLE                   102
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDI_SC4EXPAND                   107
#define IDC_MEGAEDX                     109
#define IDD_PAL                         131
#define IDD_TILESET                     132
#define IDD_MAP                         137
#define IDD_BLOCK                       140
#define IDR_241                         141
#define IDB_TELEPORT                    142
#define IDB_XSPRITE                     143
#define IDD_SCENE                       146
#define IDB_TOOLBAR                     147
#define IDD_SETTINGS                    148
#define IDD_OFFSETS                     149
#define IDD_SPRITE                      149
#define IDB_MEGAEDXLOGO                 150
#define IDD_EVENT                       150
#define IDR_MENU1                       151
#define IDD_PROPERTY                    154
#define IDD_CHECKPOINT                  155
#define IDD_INTERNALEMULATORSETTINGS    156
#define IDI_SC4ED                       156
#define IDR_RCDATA1                     163
#define IDC_PALETTEN                    1006
#define IDC_PALETTES                    1007
#define IDC_LTILEPROP                   1008
#define IDC_LTILEINDEX                  1009
#define IDC_MAPFLIP                     1013
#define IDC_MAPMIRROR                   1014
#define IDC_MAPUPLAYER                  1015
#define ID_EDITOR_BLOCKED               1022
#define ID_EDITOR_MAPED                 1023
#define ID_EDITOR_PALED                 1024
#define ID_EDITOR_SCENED                1025
#define ID_FILE_IMPORT                  1026
#define ID_FILE_OPEN                    1027
#define ID_EDITOR_TILESETED             1028
#define ID_FILE_SAVE                    1029
#define ID_FILE_SETTINGS                1030
#define ID_FILE_OFFSETS                 1031
#define ID_HELP_DONATE                  1032
#define IDM_EXIT                        1033
#define IDC_SCENED_LSCENE               1038
#define IDC_EMUPATH                     1039
#define IDC_SCENED_LSCENE2              1039
#define IDC_ERASEEMUPATH                1040
#define IDC_SCENED_LSCENE3              1040
#define IDC_SETTINGS_BROWSE             1040
#define IDC_LOADROMSTARTUP              1041
#define IDC_SCENED_LSCENE4              1041
#define IDC_SCENED_LSCENE5              1042
#define IDC_BLOCK_UL_S                  1047
#define IDC_SPALETTEN                   1049
#define IDC_SPALETTES                   1050
#define IDC_SPALETTEN2                  1053
#define IDC_SPALETTES2                  1054
#define IDC_SPALETTEN3                  1055
#define IDC_EVENT_TILEBUMP              1055
#define IDC_SPALETTES3                  1056
#define IDC_EVENT_FLAG1                 1061
#define IDC_EVENT_FLAG2                 1062
#define IDC_EVENT_LOCKSUBID             1063
#define IDC_EVENT_LOCKID                1064
#define IDC_EVENT_LOCKTYPE              1065
#define IDC_EVENT_GFXREVERSE            1066
#define IDC_EVENT_ADD                   1067
#define IDC_EVENT_DELETE                1068
#define IDC_EVENT_PREV                  1069
#define IDC_EVENT_NEXT                  1070
#define IDC_EVENT_MOVE                  1071
#define IDC_EVENT_SORT                  1071
#define IDC_EVENT_TILEBUMPNEG           1072
#define IDC_EVENT_SLOT                  1072
#define IDC_EVENT_GFXNOASSEMBLY         1073
#define IDC_REMAINING_BYTE              1074
#define IDC_REMAINING_BYTE2             1075
#define IDC_REFRESHMAIN                 1075
#define IDC_EVENT_LOCKCAMERADIR         1076
#define IDC_IEKEYUP                     1076
#define IDC_IEKEYDOWN                   1077
#define IDC_IEKEYLEFT                   1078
#define IDC_IEKEYRIGHT                  1079
#define IDC_IESAVE                      1080
#define IDC_IEJOYNUM                    1081
#define IDC_LIST1                       1083
#define IDC_PROPERTY_LIVES              1085
#define IDC_PROPERTY_CONTINUE_LIVES     1086
#define IDC_SPIN1                       1087
#define IDC_IEKEYA                      1088
#define IDC_SPIN2                       1088
#define IDC_MAP_COPY                    1088
#define IDC_IEKEYB                      1089
#define IDC_MAP_PASTE                   1089
#define IDC_PROPERTY_WHIPLENGTH         1089
#define IDC_IEKEYX                      1090
#define IDC_TILE_COPY                   1090
#define IDC_SPIN3                       1090
#define IDC_IEKEYY                      1091
#define IDC_TILE_PASTE                  1091
#define IDC_TILE_TYPE_COMBO             1092
#define IDC_PROPERTY_TIMER              1093
#define IDC_SPIN5                       1094
#define IDC_TILE_COLL_COMBO             1094
#define IDC_PROPERTY_CAMERA_LEFT        1095
#define IDC_IEKEYL                      1096
#define IDC_PROPERTY_CAMERA_RIGHT       1096
#define IDC_BLOCK_TYPE_COMBO            1096
#define IDC_IEKEYR                      1097
#define IDC_PROPERTY_CAMERA_TOP         1097
#define IDC_REMAINING_EVENTS            1097
#define IDC_IEKEYSELECT                 1098
#define IDC_PROPERTY_CAMERA_BOTTOM      1098
#define IDC_IEKEYSTART                  1099
#define IDC_PROPERTY_LEVEL_TYPE         1099
#define IDC_IEKEYNEXTSTATE              1100
#define IDC_PROPERTY_WHIP_COMBO         1100
#define IDC_IEKEYPREVSTATE              1101
#define IDC_PROPERTY_WHIPFULLDAMAGE     1101
#define IDC_IEKEYSAVESTATE              1102
#define IDC_PROPERTY_ENTRANCE_RECORD    1102
#define IDC_IEKEYLOADSTATE              1103
#define IDC_PROPERTY_WHIPPARTIALDAMAGE  1103
#define IDC_IEKEYFASTFORWARD            1104
#define IDC_PROPERTY_LEVEL_DEATH_LEVEL  1104
#define IDC_PROPERTY_MOVE_COMBO         1105
#define IDC_IEVOLUME                    1105
#define IDC_PROPERTY_MOVEPIXEL          1106
#define IDC_SPIN4                       1107
#define IDC_PROPERTY_MOVESUBPIXEL       1108
#define IDC_DROPX                       1108
#define IDC_PROPERTY_LEVEL_CONTINUE_LEVEL 1109
#define IDC_DROPX2                      1109
#define IDC_DROPY                       1109
#define IDC_IECANCEL                    1112
#define IDC_PROPERTY_CHECKPOINT_COMBO   1115
#define IDC_PROPERTY_CHECKPOINT_STATE0  1116
#define IDC_PROPERTY_CHECKPOINT_YPOS    1117
#define IDC_PROPERTY_CAMERALOCK_COMBO   1118
#define IDC_PROPERTY_CHECKPOINT_CAM0YPOS 1119
#define IDC_PROPERTY_CHECKPOINT_CAM1XPOS 1120
#define IDC_PROPERTY_CHECKPOINT_CAM1YPOS 1121
#define IDC_PROPERTY_NEXTLEVEL_COMBO    1122
#define IDC_PROPERTY_CAMERALOCK_DIRECTION 1123
#define IDC_PROPERTY_CHECKPOINT_STATE1  1124
#define IDC_PROPERTY_CHECKPOINT_XPOS    1125
#define IDC_PROPERTY_CHECKPOINT_CAM0XPOS 1126
#define IDC_PROPERTY_CAMERALOCK_DIRADDR 1127
#define IDC_PROPERTY_CAMERALOCK_CMPADDR 1128
#define IDC_PROPERTY_CAMERALOCK_CMPVALUE 1129
#define IDC_PROPERTY_CAMERALOCK_STVALUE 1130
#define IDC_PROPERTY_CAMERALOCK_STADDR  1131
#define IDC_PROPERTY_NEXTLEVEL_NEXTLEVEL 1132
#define IDC_PROPERTY_NEXTLEVEL_ENTRANCENUM 1133
#define IDC_PROPERTY_NEXTLEVEL_DEATHNUM 1134
#define IDC_PROPERTY_EXITCHECK_CMPVALUE 1136
#define IDC_PROPERTY_EXITCHECK_COMBO    1137
#define IDC_PROPERTY_EXITCHECK_TYPE     1139
#define IDC_PROPERTY_EXITCHECK_EXITNUM  1140
#define ID_IMPORT_FROMASNESGAME         32824
#define ID_IMPORT_FROMAGENESISGAME      32825
#define ID_IMPORT_FROMAGBAGAME          32826
#define ID_IMPORT_SNES                  32827
#define ID_IMPORT_GEN                   32828
#define ID_IMPORT_GBA                   32829
#define ID_FILE_SAVEAS                  32830
#define ID_EDITOR_SPRITEEDITOR          32831
#define ID_EDITOR_SPRITED               32832
#define ID_EDITOR_EVENTEDITOR           32833
#define ID_EDITOR_EVENTED               32834
#define ID_EDITOR_PROPERTYEDITOR        32835
#define ID_EDITOR_PROPERTYED            32836
#define ID_EDITOR_CHECKPOINTEDITOR      32837
#define ID_EDITOR_CHECKPOINTED          32838
#define ID_FILE_RUNINTERNALEMULATOR     32839
#define ID_Menu                         32840
#define ID_FILE_INTERNALEMULATORSETTINGS 32841
#define ID_FILE_EXPANDROM               32842
#define ID_FILE_SAVELEVELAS             32843
#define ID_FILE_LOADROOM                32844
#define ID_FILE_SAVEROOMAS              32845
#define ID_FILE_LOADLEVEL               32846
#define IDC_LMAPINDEX                   0x9000
#define IDC_LBLOCKINDEX                 0x9200
#define IDC_LMAPTILEINDEX               37377
#define IDC_LBLOCKINDEX3                37378
#define IDC_LBLOCKINDEX4                37379
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
